### PR TITLE
specify the separator?

### PR DESCRIPTION
**Pull request by rudyrichter**
Jack asked me if I might be able to let him customize the separator via a "defaults write", wiring it up to an actual text field beyond that initial request not terribly hard so I wired something up. I wasn't sure if it should also replace the separator inside of the "copy the clipboard" remainder or not, so right now it still has it as re-composing with `:`

### CODE REVIEW

**Comment by crankygeek** [comment]
@iconmaster Any thoughts on merging this? (After fixing the conflicts, of course :) )

**Comment by iconmaster** [comment]
I'm hoping @rudyrichter will sort it out, though I'm really the one who broke his code here. I had to do some refactoring and I'm not sure what, if anything, it means for his work. `annotationSeparator` is at least a variable now, so tying it to a preference should be straightforward.

**Comment by rudyrichter** [comment]
@iconmaster i'll look at it this weekend probably

**Comment by rudyrichter** [comment]
@iconmaster pushed up some changes; any objection to another PR that refactors a couple things?

**Comment by iconmaster** [comment]
This isn't quite working correctly. Consider the string:

`Annotation and note: the note is the part copied.`

When I click the menu item for that string in the MenuBrain menu, the part copied to the clipboard should be `the note is the part copied.`. This works on `master`, but in the PR the whole string is copied. maybe make sure `annotationSeparator` is really getting the value from the Separator default?

**Comment by rudyrichter** [comment]
@iconmaster that does seem to be working here, did you change the separator value to something else?

**Comment by iconmaster** [comment]
Something in your code breaks the reference to `annotationSeparator`. Querying it at the end of `awakeFromNib` works fine on `master`, but fails here. That's why MenuBrain isn't splitting items correctly.

image

**Comment by iconmaster** [comment]
For posterity: I'm a dork. I had a pre-existing `default` confusing the whole matter.

**Pull request merged**
